name:                buildScriptBuilder
version:             0.1.0.0
github:              "Merckinator/buildScriptBuilder"
license:             MIT
author:              "Jeff Merckens"
maintainer:          "jeff.merckens@gmail.com"
copyright:           "2019 Jeff Merckens"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Merckinator/buildScriptBuilder#readme>

dependencies:
- base >= 4.7 && < 5
- directory

library:
  source-dirs: src

executables:
  buildScriptBuilder-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - buildScriptBuilder

tests:
  buildScriptBuilder-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - buildScriptBuilder
